### ISSUE TITLE
Use double quotes everywhere

### ISSUE THREAD

**Issue by ne1ro** [fs/eslint-config-fs#1]
`"quotes": ["error", "double"]`

**Comment by maratfakhreev** [comment]
@ne1ro sorry, but js community prefers single quotes for strings. 

For example: https://github.com/airbnb/javascript#strings--quotes

**Comment by ne1ro** [comment]
@maratfakhreev I know, but double quotes are used in HTML and JSX - this looks inconsistent and contradictory.

**Comment by maratfakhreev** [comment]
@ne1ro yeah, in many ways I agree with you, but in jsx is prefered to use double quotes, it's probably not so clear in one file see two type of quotes however jsx is looking as another format (like XML/HTML) with its own rules. Besides, we have become accustomed to this style)
